# src/main/resources/application-example.yml
spring:
  datasource:
    url: jdbc:postgresql://<HOST>:<PORT>/<DB>
    username: <USER>
    password: <PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
# 実運用では Render の環境変数 DB_URL / DB_USER / DB_PASSWORD を使ってください
